server:
  port: 9000

spring:
  application:
    name: order
  rabbitmq:
    host: 192.168.10.114
    username: hqq
    password: 123
    port: 5672
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://edward:123@eurekaserver1:8761/eureka  #,http://edward:123@eurekaserver2:8001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
env:  dev
